<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'Tủ gỗ trang trí1',
                'slug' => 'sofa-don-hien-dai',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 3200000,
                'quantity' => 10,
                'category_id' => 4,
                'image' => 'sofa-don.webp',
                'created_at' => now(),
                'views' => 30,
                'sale_price' => 3006934,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Sofa giường đa năng',
                'slug' => 'sofa-giuong-da-nang',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 5500000,
                'quantity' => 5,
                'category_id' => 4,
                'image' => 'sofa-giuong.webp',
                'created_at' => now(),
                'views' => 20,
                'sale_price' => 5385274,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Sofa da cao cấp',
                'slug' => 'sofa-da-cao-cap',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 7800000,
                'quantity' => 7,
                'category_id' => 4,
                'image' => 'sofa-da.webp',
                'created_at' => now(),
                'views' => 12,
                'sale_price' => 7605865,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Sofa vải nhung',
                'slug' => 'sofa-vai-nhung',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 4600000,
                'quantity' => 12,
                'category_id' => 4,
                'image' => 'sofa-vai.webp',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 4473802,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Sofa 3 chỗ bọc nỉ',
                'slug' => 'sofa-3-cho-boc-ni',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 5200000,
                'quantity' => 6,
                'category_id' => 4,
                'image' => 'sofa-3-cho.webp',
                'created_at' => now(),
                'views' => 63,
                'sale_price' => 5051717,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Sofa góc chữ U',
                'slug' => 'sofa-goc-chu-u',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 8900000,
                'quantity' => 4,
                'category_id' => 4,
                'image' => 'sofa-goc-u.webp',
                'created_at' => now(),
                'views' => 25,
                'sale_price' => 8737478,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Đèn bàn LED',
                'slug' => 'den-ban-led',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 450000,
                'quantity' => 20,
                'category_id' => 5,
                'image' => 'den-ban.webp',
                'created_at' => now(),
                'views' => 65,
                'sale_price' => 380000,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Đèn cây đứng',
                'slug' => 'den-cay-dung',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1200000,
                'quantity' => 15,
                'category_id' => 5,
                'image' => 'den-cay.webp',
                'created_at' => now(),
                'views' => 23,
                'sale_price' => 1050561,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Đèn ngủ để bàn',
                'slug' => 'den-ngu-de-ban',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 350000,
                'quantity' => 30,
                'category_id' => 5,
                'image' => 'den-ngu.jpg',
                'created_at' => now(),
                'views' => 45,
                'sale_price' => 205486,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Đèn treo trần hiện đại',
                'slug' => 'den-treo-tran-hien-dai',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 2500000,
                'quantity' => 10,
                'category_id' => 5,
                'image' => 'den-treo-tran.webp',
                'created_at' => now(),
                'views' => 26,
                'sale_price' => 2326048,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Đèn led dây trang trí',
                'slug' => 'den-led-day-trang-tri',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 200000,
                'quantity' => 50,
                'category_id' => 5,
                'image' => 'den-led-day.webp',
                'created_at' => now(),
                'views' => 42,
                'sale_price' => 64082,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Đèn thả trần',
                'slug' => 'den-tha-tran',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1800000,
                'quantity' => 8,
                'category_id' => 5,
                'image' => 'den-tha.webp',
                'created_at' => now(),
                'views' => 46,
                'sale_price' => 1642564,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Giường tầng gỗ',
                'slug' => 'giuong-tang-go',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 7500000,
                'quantity' => 5,
                'category_id' => 6,
                'image' => 'giuong-tang.jpg',
                'created_at' => now(),
                'views' => 36,
                'sale_price' => 7320873,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Giường ngủ đơn',
                'slug' => 'giuong-ngu-don',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 3200000,
                'quantity' => 10,
                'category_id' => 6,
                'image' => 'giuong-don.webp',
                'created_at' => now(),
                'views' => 49,
                'sale_price' => 3076975,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Giường ngủ đôi',
                'slug' => 'giuong-ngu-doi',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 5800000,
                'quantity' => 7,
                'category_id' => 6,
                'image' => 'giuong-doi.jpg',
                'created_at' => now(),
                'views' => 15,
                'sale_price' => 5622554,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Giường pallet gỗ',
                'slug' => 'giuong-pallet-go',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 4000000,
                'quantity' => 12,
                'category_id' => 6,
                'image' => 'giuong-pallet.jpg',
                'created_at' => now(),
                'views' => 62,
                'sale_price' => 3882144,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Giường ngủ bọc nỉ',
                'slug' => 'giuong-ngu-boc-ni',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 6200000,
                'quantity' => 6,
                'category_id' => 6,
                'image' => 'giuong-boc-ni.jpg',
                'created_at' => now(),
                'views' => 42,
                'sale_price' => 6043358,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Giường ngủ có hộc kéo',
                'slug' => 'giuong-ngu-co-hoc-keo',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 6800000,
                'quantity' => 4,
                'category_id' => 6,
                'image' => 'giuong-hoc-keo.jpg',
                'created_at' => now(),
                'views' => 42,
                'sale_price' => 6670658,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Cây lưỡi hổ',
                'slug' => 'cay-luoi-ho',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 250000,
                'quantity' => 25,
                'category_id' => 7,
                'image' => 'cay-luoi-ho.webp',
                'created_at' => now(),
                'views' => 66,
                'sale_price' => 73515,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Cây kim tiền',
                'slug' => 'cay-kim-tien',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 380000,
                'quantity' => 20,
                'category_id' => 7,
                'image' => 'cay-kim-tien.webp',
                'created_at' => now(),
                'views' => 25,
                'sale_price' => 185902,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Cây sen đá',
                'slug' => 'cay-sen-da',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 150000,
                'quantity' => 50,
                'category_id' => 7,
                'image' => 'cay-sen-da.webp',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 9265,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Cây trầu bà leo',
                'slug' => 'cay-trau-ba-leo',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 320000,
                'quantity' => 18,
                'category_id' => 7,
                'image' => 'cay-trau-ba.webp',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 198916,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Cây bàng Singapore',
                'slug' => 'cay-bang-singapore',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 950000,
                'quantity' => 8,
                'category_id' => 7,
                'image' => 'cay-bang.webp',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 767085,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Cây xương rồng mini',
                'slug' => 'cay-xuong-rong-mini',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 100000,
                'quantity' => 40,
                'category_id' => 7,
                'image' => 'cay-xuong-rong.webp',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => -51025,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Bàn làm việc gỗ sồi',
                'slug' => 'ban-lam-viec-go-soi',
                'description' => '17 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 2600000,
                'quantity' => 11,
                'category_id' => 1,
                'image' => 'ban-go-soi.webp',
                'created_at' => now(),
                'views' => 4,
                'sale_price' => 2393920,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Bàn trà hiện đại',
                'slug' => 'ban-tra-hien-dai',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1800000,
                'quantity' => 15,
                'category_id' => 1,
                'image' => 'ban-tra.webp',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1622973,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Bàn học thông minh',
                'slug' => 'ban-hoc-thong-minh',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 2100000,
                'quantity' => 12,
                'category_id' => 1,
                'image' => 'ban-hoc.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1933406,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Bàn tròn cafe',
                'slug' => 'ban-tron-cafe',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1600000,
                'quantity' => 20,
                'category_id' => 1,
                'image' => 'ban-tron.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1498412,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Bàn xếp gọn',
                'slug' => 'ban-xep-gon',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1900000,
                'quantity' => 10,
                'category_id' => 1,
                'image' => 'ban-xep.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1792143,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Ghế xoay văn phòng',
                'slug' => 'ghe-xoay-van-phong',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1400000,
                'quantity' => 15,
                'category_id' => 2,
                'image' => 'ghe-xoay.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1265775,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Ghế gỗ tự nhiên',
                'slug' => 'ghe-go-tu-nhien',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1200000,
                'quantity' => 20,
                'category_id' => 2,
                'image' => 'ghe-go.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1052745,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Ghế sofa đơn',
                'slug' => 'ghe-sofa-don',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 2300000,
                'quantity' => 10,
                'category_id' => 2,
                'image' => 'ghe-sofa.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 2166701,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Ghế nhựa cao cấp',
                'slug' => 'ghe-nhua-cao-cap',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 900000,
                'quantity' => 25,
                'category_id' => 2,
                'image' => 'ghe-nhua.webp',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 775567,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Ghế thư giãn gấp gọn',
                'slug' => 'ghe-thu-gian-gap-gon',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1700000,
                'quantity' => 12,
                'category_id' => 2,
                'image' => 'ghe-thu-gian.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1578035,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Ghế ăn sang trọng',
                'slug' => 'ghe-an-sang-trong',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 1300000,
                'quantity' => 18,
                'category_id' => 2,
                'image' => 'ghe-an.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1163773,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Tủ quần áo 3 cánh',
                'slug' => 'tu-quan-ao-3-canh',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 4200000,
                'quantity' => 8,
                'category_id' => 3,
                'image' => 'tu-quan-ao.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 4085057,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Tủ giày thông minh',
                'slug' => 'tu-giay-thong-minh',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 2100000,
                'quantity' => 12,
                'category_id' => 3,
                'image' => 'tu-giay.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 1934269,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Tủ bếp gỗ tự nhiên',
                'slug' => 'tu-bep-go-tu-nhien',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 5800000,
                'quantity' => 5,
                'category_id' => 3,
                'image' => 'tu-bep.png',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 5616470,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Tủ sách nhiều ngăn',
                'slug' => 'tu-sach-nhieu-ngan',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 2700000,
                'quantity' => 15,
                'category_id' => 3,
                'image' => 'tu-sach.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 2579845,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Tủ đựng tài liệu',
                'slug' => 'tu-dung-tai-lieu',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 3300000,
                'quantity' => 10,
                'category_id' => 3,
                'image' => 'tu-ho-so.jpg',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 3150114,
                'updated_at' => NULL,
            ],
            [
                'name' => 'Tủ gỗ trang trí',
                'slug' => 'tu-go-trang-tri',
                'description' => '7 ngày hoàn trả miễn phí',
                'rating' => 4.5,
                'price' => 2900000,
                'quantity' => 12,
                'category_id' => 3,
                'image' => 'tu-trang-tri.webp',
                'created_at' => now(),
                'views' => 0,
                'sale_price' => 2711336,
                'updated_at' => NULL,
            ],


            // Add other items here...



            // Thêm các sản phẩm còn lại theo kiểu trên
        ]);
    }
}
